spring.application.name=checkpoint2

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cp2_soa
spring.datasource.username=root
spring.datasource.password=62800750pietro

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
